config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/about_us', to: 'pages#about_us', as: :about_us

  resources :projects do
  	resources :surveys, except: [ :show, :edit, :destroy, :index]
  end
  resources :surveys, only: [ :show, :destroy, :index] do
    resources :survey_questions, only: [:create, :update]
    resources :question_answers, except: [:edit, :update, :destroy]
    resources :welcome_messages, only: [:new, :create]
    resources :thankyou_screens, only: [:create]
  end

  resources :survey_questions, except: [ :update, :create]

  resources :participants, except: [:edit, :update, :destroy]

  resources :users, path: '', only: [:show]



  post 'surveys/feature', to: 'surveys#feature', as: :feature_survey


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>

  <div class="navbar-home signed-in">

    <a href="/"><%= image_tag "logo2.png", alt: "logo2", class:"logo2 navbar-item" %></a>

    <%= link_to "PROJECTS", projects_path, class: "navbar-item #{params[:controller] == "projects" ? "selected-menu-item" : ""}"  %>
    <%= link_to "SURVEYS", surveys_path, class: "navbar-item #{params[:controller] == "surveys" ? "selected-menu-item" : ""}" %>
    <%= link_to "ABOUT US", about_us_path, class: "navbar-item #{params[:action] == "about_us" ? "selected-menu-item" : ""}" %>

    <div class="dropdown">
      <button class="btn navbar-item sec-button" type="button" id="dropdownMenuButton" data-toggle="dropdown">MY ACCOUNT</button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "Profile", user_path(current_user), class: "dropdown-item"  %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
    <%#= link_to "MY ACCOUNT", user_path(current_user), class: "navbar-item sec-button" %>
  </div>
<% else %>
  <div class="navbar-home signed-in">
      <!-- <a href="#", class="navbar-item">ABOUT</a>
      <a href="#", class="navbar-item">PRICING</a>
      <a href="#", class="navbar-item">BLOG</a> -->
      <%#= link_to "ABOUT US", root_path, class: "navbar-item" %>
      <%= link_to "LOGIN", new_user_session_path, class: "navbar-item sec-button" %>
      <%= link_to "SIGN UP", new_user_registration_path, class: "navbar-item sec-button" %>
    </div>
<% end %>

app/views/shared/_test.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <div class="navbar-home">
        <li class="navbar-item">
          <%= link_to "ABOUT", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="navbar-item">
          <%= link_to "PRICING", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="navbar-item">
          <%= link_to "BLOG", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="navbar-item">
          <%= link_to "LOGIN", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="navbar-item">
          <%= link_to "SIGN UP", new_user_session_path, class: "nav-link" %>
        </li>
      </div>
      <% end %>
    </ul>
  </div>
</div>