config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/about_us', to: 'pages#about_us', as: :about_us

  resources :projects do
  	resources :surveys, except: [ :show, :edit, :destroy, :index]
  end
  resources :surveys, only: [ :show, :destroy, :index] do
    resources :survey_questions, only: [:create, :update]
    resources :question_answers, except: [:edit, :update, :destroy]
    resources :welcome_messages, only: [:new, :create]
    resources :thankyou_screens, only: [:create]
  end

  resources :survey_questions, except: [ :update, :create]

  resources :participants, except: [:edit, :update, :destroy]

  resources :users, path: '', only: [:show]



  post 'surveys/feature', to: 'surveys#feature', as: :feature_survey


end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :surveys, dependent: :destroy
  has_many :participants, through: :surveys

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  def index
    # @projects = policy_scope(Project)
    # authorize @projects
    @projects = Project.all.reverse
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @token = ENV["TYPEFORM_API_TOKEN"]
    @project = Project.new(project_params)
    @project.user_id = current_user.id

     if @project.save
      begin
        response =
          RestClient.post(
            "https://api.typeform.com/themes", {
              "background": {
              "href": "https://images.typeform.com/images/VB37Vp7QpDiQ",
                "layout": "fullscreen"
              },
              "colors": {
                "answer": "#FCCD08",
                "background": "#F8F8F8",
                "button": "#413D56",
                "question": "#413D56"
              },
              "font": "Karla",
              "has_transparent_button": false,
              "name": "dcme.today",
              "visibility": "private"
            }.to_json, Authorization: "bearer #{@token}")

      rescue Exception =>
        raise
      end
      @response = JSON.parse(response)
      @project.theme = @response["id"]
      @project.save

      redirect_to projects_path
    end
  end

  def edit
  end

  def update
    @project.update(params[project_params])
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
    # authorize @project # For Pundit, CHECK necessity!
  end

  def project_params
    params.require(:project).permit(:name) # CHANGE HERE!
  end
end

app/views/projects/_add_project.html.erb
<%= link_to "#{project.name}", project_path(project) %>

app/views/projects/_new_project.html.erb
<div class="modal fade" id="create-new-project" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Name</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(Project.new) do |f| %>
          <%= f.input :name, label: false %>
          <%= f.button :submit, class: "button", value:"Create new Project", class: "filled-button-survey" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/create.js.erb
function refreshForm(innerHTML) {
  const newProjectForm = document.getElementById('new_project');
  newProjectForm.innerHTML = innerHTML;
}

function addProject(projectHTML) {
  const projects = document.getElementById('projects');
  projects.insertAdjacentHTML('beforeend', projectHTML);
}


addProject('<%= j render "projects/add_project", project: @project %>');
refreshForm('<%= j render "projects/new_project", project: Project.new %>');

app/views/projects/index.html.erb
<% require "time"
%>

<% if current_user.projects.any? %>

<div class="container">
  <div class="row">
  	<h1 class="p-3 underline">My Projects <a href="#" data-toggle="modal" data-target="#create-new-project"><i class="fas fa-plus-circle" id="plus-btn"></i></a></h1>
    <%= render 'projects/new_project' %>
  </div>

  <div class="row align-items-center border-bottom justify-content-center pt-4 pb-2 text-center">
  	<div class="col-md-1">
      	<span><strong>Bookmark</strong></span>
      </div>
      <div class="col-md-2">
      	<span><strong>Project Name</strong></span>
      </div>
      <div class="col-md-2">
      	<span><strong>Status</strong></span>
      </div>
      <div class="col-md-1">
        <span><strong>Participants</strong></span>
      </div>
      <div class="col-md-1">
          <span><strong>Surveys</strong></span>
      </div>
      <div class="col-md-2">
        <span><strong>Updated</strong></span>
      </div>
      <div class="col-md-1">
  	  <span><strong>Edit</strong></span>
  	</div>
      <div class="col-md-1">
      	<span><strong>Delete</strong></span>
      </div>
  </div>

  <% current_user.projects.reverse.each do |project| %>
  	<% time_diff = Time.now - project.created_at %>
  	<% time_diff_days = (time_diff.fdiv(43200)).floor %>
  	<div class="row align-items-center border-bottom justify-content-center py-5 text-center hoverable">
  		<div class="col-md-1">
      		<a href="#" ><i class="purple far fas fa-star m-2"></i></a>
      	</div>
  	    <div class="col-md-2">
  	    	<%= link_to "#{project.name}", project_path(project), style:"color:black" %>
  	    </div>
  	    <div class="col-md-2">
      		<% if project.completed %>
      			<p class="project completed rounded">Completed</p>
      		<% elsif time_diff_days <= 1 %>
      			<p class="project ongoing rounded">Ongoing</p>
      		<% else %>
      			<p class="project new rounded">New</p>
      		<% end %>
      	</div>
  	    <div class="col-md-1">
  	    	<a href="#"><i class="purple fas fa-users"></i></a>
  	    	<%= project.participants.count %>
  	    </div>
  	    <div class="col-md-1">
  	    	<a href="#"><i class="purple fas fa-poll"></i></i></a>
  	        <%= project.surveys.count %>
  	    </div>
  	    <div class="col-md-2">
  	      <%= time_diff_days.to_s + " Days Ago" if time_diff_days > 1  %>
          <%= "Yesterday" if time_diff_days == 1 %>
          <%#= "Today" if time_diff_days == 0 %>
          <%= project.created_at if project.created_at.class == String %>
  	    </div>
  	    <div class="col-md-1">
  	    	<a href="#"><i class="fan fas fa-edit"></i></a>
  	    </div>
  	    <div class="col-md-1">
  	    	<%= link_to '<i class="fan fas fa-trash-alt"></i>'.html_safe, project_path(project), method: :delete, data: {confirm: "Are you sure?"} %>
  	    </div>
  	</div>
  <% end %>
  </div>

<% else %>

  <div class="row">
    <h1 class="p-3 underline">My Projects</h1>
  </div>

  <div class="mt-3">
   <p style="font-style: italic; opacity: 0.5">No projects have been added</p>
   <div class="d-flex align-items-center ">
    <p class="mb-0 mr-2"> Create one here!</p>
    <a href="#" data-toggle="modal" data-target="#create-new-project"><i class="fas fa-plus-circle" id="plus-btn"></i></a>
    <%= render 'projects/new_project' %>
  </div>
  </div>

<% end %>

app/views/projects/new.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "button", value:"Create new Project", class: "filled-button" %>
<% end %>

app/views/projects/show.html.erb
<% require "time"
%>


<!-- <div class="row">
	<p class="p-3 m-0">Description of Project</i></p>
	<p class="p-3 m-0"><%#= @project.participants.count %> <i class="fas fa-users"></i></p>
	<p class="p-3 m-0"><%#= @project.surveys.count %> <i class="fas fa-poll"></i></p>
</div> -->

<% if @project.surveys.any? %>

<div class="container">
	<%= link_to '<i class="fas purple fa-arrow-circle-left"></i>'.html_safe, projects_path%>
 	<div class="row">

    <h1 class="p-3 underline"><%= @project.name %><a href="#" data-toggle="modal" data-target="#create-new-survey"><i class="fas fa-plus-circle ml-2" id="plus-btn"></i></a></h1>
    <%= render 'surveys/new_survey', project: @project %>
  </div>

	<div class="row align-items-center border-bottom justify-content-center pt-4 pb-2 text-center">
		<div class="col-md-1">
	    	<span><strong>Bookmark</strong></span>
	    </div>
	    <div class="col-md-3">
	    	<span><strong>Survey</strong></span>
	    </div>
	    <div class="col-md-2">
	      <span><strong># of Participants</strong></span>
	    </div>
	    <div class="col-md-2">
	        <span><strong># of Questions</strong></span>
	    </div>
	    <div class="col-md-2">
	      <span><strong>Updated</strong></span>
	    </div>
	    <div class="col-md-1">
		  <span><strong>Edit</strong></span>
		</div>
	    <div class="col-md-1">
	    	<span><strong>Delete</strong></span>
	    </div>
	  </div>

	<% @project.surveys.each do |survey| %>
		<div class="row align-items-center border-bottom justify-content-center py-5 text-center hoverable">
			<div class="col-md-1">
	    		<a href="#"><i class="far fas purple fa-star m-2"></i></a>
	    	</div>
		    <div class="col-md-3">
		    	<%= link_to "#{survey.name}", survey_path(survey), style:"color:black" %>
          <% if survey.completed %>
            <i class="far fa-check-circle" style="color: #FCCD08"></i>
          <% end %>
		    </div>
		    <div class="col-md-2">
		    	<a href="#"><i class="fas purple fa-users"></i></a>
		    	<%= survey.participants.count %>
		    </div>
		    <div class="col-md-2">
		    	<a href="#"><i class="far fas purple fa-question-circle"></i></a>
		        <%= survey.survey_questions.count %>
		    </div>
		    <div class="col-md-2">
		      <% time_diff = Time.now - survey.created_at %>
		      <% time_diff_days = (time_diff.fdiv(43200)).floor %>
		      <%= time_diff_days.to_s + " Days Ago" if time_diff_days > 1  %>
		      <%= "Yesterday" if time_diff_days == 1 %>
		      <%= "Today" if time_diff_days == 0 %>
		    </div>
		    <div class="col-md-1">
		    	<a href="#"><i class="fas fa-edit"></i></a>
		    </div>
		    <div class="col-md-1">
		    	<%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, survey_path(survey), method: :delete, data: {confirm: "Are you sure?"} %>
		    </div>
		</div>
	<% end %>
	</div>

<% else %>

  <div class="row">
    <h1 class="p-3 underline"><%= @project.name %></h1>
  </div>

  <div class="mt-3">
	 <p style="font-style: italic; opacity: 0.5">No surveys have been added to this project yet</p>
   <div class="d-flex align-items-center ">
    <p class="mb-0 mr-2"> Create one here!</p>
    <a href="#" data-toggle="modal" data-target="#create-new-survey"><i class="fas fa-plus-circle" id="plus-btn"></i></a>
    <%= render 'surveys/new_survey', project: @project %>
  </div>
  </div>


<% end %>