config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/about_us', to: 'pages#about_us', as: :about_us

  resources :projects do
  	resources :surveys, except: [ :show, :edit, :destroy, :index]
  end
  resources :surveys, only: [ :show, :destroy, :index] do
    resources :survey_questions, only: [:create, :update]
    resources :question_answers, except: [:edit, :update, :destroy]
    resources :welcome_messages, only: [:new, :create]
    resources :thankyou_screens, only: [:create]
  end

  resources :survey_questions, except: [ :update, :create]

  resources :participants, except: [:edit, :update, :destroy]

  resources :users, path: '', only: [:show]



  post 'surveys/feature', to: 'surveys#feature', as: :feature_survey


end

app/models/survey_question.rb
class SurveyQuestion < ApplicationRecord
  belongs_to :survey

  has_many :question_answers, dependent: :destroy

  validates :q_type, presence: true
end

app/controllers/survey_questions_controller.rb
class SurveyQuestionsController < ApplicationController
  before_action :set_survey_question, only: [:show]
  # before_action :responses, only: [:show]
  before_action :set_token, only: [:destroy, :create, :update]

	def new
		@survey_question = SurveyQuestion.new
	end

  def index
    @survey_questions = SurveyQuestion.all
  end

  def show
    @survey_question = SurveyQuestion.find(params[:id])
    @survey = @survey_question.survey
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @survey_question = SurveyQuestion.new(survey_question_params)
    @survey_question.survey = @survey
    @survey_question.save
    
    respond_to do |format|
      format.html { redirect_to survey_path(@survey) }
      format.js
    end
  end

  def edit
    @survey_question = SurveyQuestion.find(params[:id])

    respond_to do |format|
      format.html { redirect_to survey_path(@survey) }
      format.js
    end
  end

  def update
    @survey_question = SurveyQuestion.find(params[:id])
    @survey = Survey.find(@survey_question.survey.id)

    if @survey_question.update(survey_question_params)

      respond_to do |format|
        format.html { redirect_to survey_path(@survey) }
        format.js
      end
    else
      render(:edit)
    end
  end

  def destroy
    @survey_question = SurveyQuestion.find(params[:id])
    @survey = Survey.find(@survey_question.survey.id)

    if @survey_question.delete

      respond_to do |format|
        format.html { redirect_to survey_path(@survey) }
        format.js
      end
    else
      render(:edit)
    end
  end

  private

  def set_survey_question
    @survey_question = SurveyQuestion.find(params[:id])
    # authorize @survey_question
  end

  def set_token
    @token = ENV["TYPEFORM_API_TOKEN"]
  end

  def survey_question_params
    params.require(:survey_question).permit(:question, :q_type)
  end
end

# Typeform Gem Code - Do not USE!
# def append_new_question
#   @form = RetrieveFormRequest.new(Form.new(id: @survey.typeform_id), token: @token).form
#   if @survey_question.q_type == "Rating Scale"
#     @form.blocks << OpinionScaleBlock.new(title: @survey_question.question)
#   elsif @survey_question.q_type == "Short Text"
#     @form.blocks << ShortTextBlock.new(title: @survey_question.question)
#   end
#   @form = UpdateFormRequest.new(@form, token: @token).form
# end

# def update_form_question
#   @form = RetrieveFormRequest.new(Form.new(id: @survey_question.survey.typeform_id), token: @token).form
#   @q_index = @form.blocks.index { |t| t.id == @survey_question.typeform_id }
#   @form.blocks[@q_index].title = @survey_question.question
#   @form = UpdateFormRequest.execute(@form, token: @token).form
# end

# def delete_form_question
#   @form = RetrieveFormRequest.new(Form.new(id: @survey_question.survey.typeform_id), token: @token).form
#   @q_index = @form.blocks.index { |t| t.id == @survey_question.typeform_id }
#   @form.blocks.delete_at(@q_index)
#   @form = UpdateFormRequest.new(@form, token: @token).form
# end

app/views/survey_questions/_add_question.html.erb
<!-- <div id="q-<%= question.id %>" class="d-inline-flex">

  <div class="col-12 col-lg-8 col-xl-8">

  </div>

  <div class="col-12 col-lg-2 col-xl-2">
  </div>

  <div class="col-12 col-lg-2 col-xl-2">
  </div>

</div>
 -->

<div class="row align-items-center justify-content-center text-center hoverable" id="q-<%= question.id %>">
  <div class="col-md-1">
    <%= counter %>
  </div>
  <div class="col-md-5">
    <%= question.question %>
   </div>
  <div class="col-md-4 q-type-indicator">
    <% if question.q_type == "short_text" %>
      <p class="question-type-text">Text</p>
    <% elsif question.q_type == "email" %>
      <p class="question-type-email">Email</p>
    <% elsif question.q_type == "opinion_scale" %>
      <p class="question-type-opinion-scale">Opinion Scale</p>
    <% end %>
  </div>

  <% if !@survey.completed %>
  <div class="col-md-1">
    <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_survey_question_path(question.id), remote: true, class: "edit-icon"  %>
  </div>
  <div class="col-md-1">
    <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, survey_question_path(question.id), remote: true, method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
  <% end %>
</div>

app/views/survey_questions/_new_question.html.erb
<% if question.new_record? %>

  <%= simple_form_for([survey, question], validate: true) do |f| %>

    <%#= f.input :q_type, collection: [

      [image_tag("email_small_yellow.png").html_safe, 'email'],
      [image_tag("text_small_yellow.png").html_safe, 'short_text'],
      [image_tag("opinion_small_yellow.png").html_safe, 'opinion_scale']
      ], as: :radio_buttons   %>

      <fieldset class="form-group radio_buttons required survey_question_q_type">
        <legend class="col-form-label pt-0" style="font-size: 18px;"><strong>Please choose a Question Type *</strong></legend>
        <input type="hidden" name="survey_question[q_type]" value="">

        <div class="form-check">
          <input class="form-check-input radio_buttons required" type="radio" value="email" name="survey_question[q_type]" id="survey_question_q_type_email">
          <label class="form-check-label collection_radio_buttons" for="survey_question_q_type_email">
          <%= image_tag "question_icons/email.png" %>
          </label>
          <p class="mt-2 label-form">Email</p>
        </div>

        <div class="form-check">
          <input class="form-check-input radio_buttons required" type="radio" value="short_text" name="survey_question[q_type]" id="survey_question_q_type_short_text">
          <label class="form-check-label collection_radio_buttons" for="survey_question_q_type_short_text">
          <%= image_tag "question_icons/text.png", alt: "alttext" %>
          </label>
          <p class="mt-2 label-form">Text Box</p>
        </div>

        <div class="form-check">
          <input class="form-check-input radio_buttons required" type="radio" value="opinion_scale" name="survey_question[q_type]" id="survey_question_q_type_opinion_scale">
          <label class="form-check-label collection_radio_buttons" for="survey_question_q_type_opinion_scale">
          <%= image_tag "question_icons/opinion.png" %>
        </label>
        <p class="mt-2 label-form">Opinion Scale</p>
        </div>
      </fieldset>

    <%= f.input :question,label: "Type in your question:", placeholder: "Waiting for your question...", style: "font-size: 18px"  %>
    <%= f.button :submit, value: "Add Question", class: "button outline-button" %>
  <% end %>

<% else %>

  <%= simple_form_for question, remote: true, :url => survey_survey_question_path(survey, question) do |f| %>
      <%= f.input :question %>
      <%= f.button :submit, class: "button outline-button"  %>
  <% end %>

<% end %>


<script>
function validateForm(){
  var question = document.getElementById('new_survey_question').value;

  if (<%= question.valid? %>) {
        document.getElementById('error-name').innerHTML = " Please Enter Your Name *"
      }
}
</script>

app/views/survey_questions/create.js.erb
function refreshForm(innerHTML) {
  const newSurveyQuestionForm = document.getElementById('new_survey_question');
  newSurveyQuestionForm.innerHTML = innerHTML;
}

function addSurveyQuestion(questionHTML) {
  const questions = document.getElementById('questions');
  questions.insertAdjacentHTML('beforeend', questionHTML);
}

<% if @survey_question.errors.empty?  %>

	document.getElementById('questions-container').innerHTML = '<%= j render "surveys/questions-container", survey: @survey %>'
  // addSurveyQuestion('<%= j render "survey_questions/add_question", question: @survey_question, survey: @survey_question.survey, counter: 5 %>');
  refreshForm('<%= j render "survey_questions/new_question", question: SurveyQuestion.new, survey: @survey %>');

<% end %>

loadOptionSelection = () => {
  checkBoxes = document.querySelectorAll(".form-check");

  checkBoxes.forEach((box) => {
    box.addEventListener('click', (event) => {
      checkBoxes.forEach( box => box.classList.remove("selected-option") )
      event.currentTarget.classList.add("selected-option")
    })
  })
}

loadOptionSelection();

app/views/survey_questions/destroy.js.erb
document.getElementById('questions-container').innerHTML = '<%= j render "surveys/questions-container", survey: @survey %>'

app/views/survey_questions/edit.js.erb
// const edit_icon = document.querySelector(".edit-icon")

  // edit_icon.addEventListener('click', (icon) => {
     edit_question = document.getElementById("q-<%= @survey_question.id %>");
    edit_question.innerHTML = '<%= j render "survey_questions/new_question", question: @survey_question, survey: @survey_question.survey  %>'

  // });

app/views/survey_questions/new.html.erb
new.html.erb

app/views/survey_questions/show.html.erb
<div class="row align-items-center justify-content-center p-5 text-center">
  <h5 class="mr-5 box"><%= link_to '<i class="fan fas fa-users"></i>'.html_safe, participants_path(survey_id: @survey.id), class:"m-2" %><%= @survey.participants.count %></h5>
  <h3>Question: <%= @survey_question.question %></h3>
  <h5 class="ml-5 box"><%= link_to '<i class="fan fas fa-poll"></i>'.html_safe, survey_question_answers_path(@survey), class:"m-2" %><%= @survey.survey_questions.count %></h5>
</div>

<!-- <div class="row border-bottom"><p>There are <%= @survey_question.question_answers.count %> reponses to this question: </p></div> -->
<div class="container">
<% if @survey_question.q_type == "opinion_scale" %>
	<% @qanswers = [] %>
	<% answers = 0 %>
	<% @survey_question.question_answers.each do |answer| %>
		<% @qanswers << answer.response.to_i %>
		<% answers += answer.response.to_i %>
	<% end %>
	<%#= pie_chart [@qanswers]  %>
	<% @average = answers.fdiv(@survey_question.question_answers.count).round %>
	<%= line_chart({0 => @survey_question.question_answers.where(response: "0").count, 1 => @survey_question.question_answers.where(response: "1").count, 2 => @survey_question.question_answers.where(response: "2").count, 3 => @survey_question.question_answers.where(response: "3").count, 4 => @survey_question.question_answers.where(response: "4").count, 5 => @survey_question.question_answers.where(response: "5").count, 6 => @survey_question.question_answers.where(response: "6").count, 7 => @survey_question.question_answers.where(response: "7").count, 8 => @survey_question.question_answers.where(response: "8").count, 9 => @survey_question.question_answers.where(response: "9").count, 10 => @survey_question.question_answers.where(response: "10").count}) %>
	<div class="row align-items-center justify-content-center pt-2 pb-1 text-center"><h5><strong>Average: <%= @average %></strong></h5></div>
<% end %>
</div>

<div class="container">
<div class="row align-items-center border-bottom justify-content-center py-3 text-left">
	<div class="col-md-1">
    	<span><strong>#</strong></span>
    </div>
    <div class="col-md-5 text-center">
    	<span><strong>Answer</strong></span>
    </div>
    <div class="col-md-3">
    	<span><strong>By</strong></span>
    </div>
    <div class="col-md-1">
    </div>
</div>


<% @survey_question.question_answers.reverse.each_with_index do |answer, i| %>
	<div class="row align-items-center border-bottom justify-content-center py-3 text-left hoverable">
		<div class="col-md-1">
	    	<%= i + 1 %>
	    </div>
		<div class="col-md-5 text-center">
	    	<% if answer.survey_question.q_type == "opinion_scale" %>
	    		<%  @value = answer.response.to_i %>
	    	  	<% if @value < @average %>
	    	  		 <%= answer.response %> /10 <i class="fas fa-arrow-down text-danger smaller"></i>
	    	  	<% elsif @value == @average %>
	    	  		 <%= answer.response %> /10 <i class="fas fa-equals smaller"></i>
	    	  	<% elsif @value > @average %>
	    	  		 <%= answer.response %> /10 <i class="fas fa-arrow-up text-success smaller"></i>
	    	  	<% end %>
	    	 <% else %>
	    	 <%= answer.response %>
	    	<% end %>
	    </div>
	    <div class="col-md-3">
	    	<%= answer.participant.email %>
	    </div>
	    <div class="col-md-1">
      		<%= link_to '<i class="fan fas fa-arrow-right"></i>'.html_safe, participant_path(answer.participant) %>
    	</div>
	</div>
<% end %>
</div>

<div class="row align-items-center justify-content-center p-3">
      <%= link_to "Go to Questions", survey_question_answers_path(@survey), class: "button filled-button m-3" %>
      <%= link_to "Go to Partipants", participants_path(survey_id: @survey.id), class: "button filled-button m-3" %>
</div>

<!-- Add navigation to previous and next question?
 --><%#= link_to '<i class="fan fas fa-arrow-right"></i>'.html_safe, survey_question_path(answer.survey_question, question_number: i) %>

app/views/survey_questions/update.js.erb
const update_question = document.getElementById("q-<%= @survey_question.id %>")
update_question.innerHTML = `<%= @survey_question.question %> <%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_survey_question_path(@survey_question.id), remote: true  %>`