config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/about_us', to: 'pages#about_us', as: :about_us

  resources :projects do
  	resources :surveys, except: [ :show, :edit, :destroy, :index]
  end
  resources :surveys, only: [ :show, :destroy, :index] do
    resources :survey_questions, only: [:create, :update]
    resources :question_answers, except: [:edit, :update, :destroy]
    resources :welcome_messages, only: [:new, :create]
    resources :thankyou_screens, only: [:create]
  end

  resources :survey_questions, except: [ :update, :create]

  resources :participants, except: [:edit, :update, :destroy]

  resources :users, path: '', only: [:show]



  post 'surveys/feature', to: 'surveys#feature', as: :feature_survey


end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :project
  has_many :welcome_messages, dependent: :destroy

  has_many :participants, dependent: :destroy
  has_many :survey_questions, dependent: :destroy
end

app/controllers/surveys_controller.rb
require 'json'
require 'rest-client'

class SurveysController < ApplicationController
  before_action :set_survey, only: [:create, :show]

  def index
    # @surveys = policy_scope(Survey)
    # authorize @surveys
    @surveys = Survey.all

    @survey = Survey.new

    @survey_question = SurveyQuestion.new
  end

  def new
    @project = Project.find(params[:project_id])
    @survey = Survey.new
  end

  def create
    @token = ENV["TYPEFORM_API_TOKEN"]
    @survey = Survey.create(survey_params)
    # authorize @survey
    @project = Project.find(params[:project_id])
    @survey.project = @project
    if @survey.save
      begin
        response =
          RestClient.post(
            "https://api.typeform.com/forms", {
              title: @survey.name,
            }.to_json, Authorization: "bearer #{@token}")

          image = RestClient.post(
            )
        rescue Exception =>
          raise
      end

      @response = JSON.parse(response)
      @survey.typeform_id = @response["id"]
      @survey.save

      redirect_to project_path(@project)
    end

  end

  def show
    @token = ENV["TYPEFORM_API_TOKEN"]
    @survey = Survey.find(params[:id])
    @survey_question = SurveyQuestion.new

    #Typeform Gem
    # if @survey.typeform_id.nil?
    #   @form = CreateFormRequest.new(Form.new(title: @survey.name), token: @token).form
    #   @survey.typeform_id = @form.id
    #    @survey.save
    # end
  end

  def edit
  end

  def update
    @token = ENV["TYPEFORM_API_TOKEN"]
    @survey = Survey.find(params[:id])
    @survey.completed = true
    @survey.save

    add_to_typeform(@survey)

    @url = 'https://api.typeform.com/'
    @url += "forms/#{@survey.typeform_id}"
    response_test = RestClient.get(@url, Authorization: "bearer #{@token}")
    @response_final = JSON.parse(response_test)

    @survey.survey_questions.each_with_index do |question, i|
      question.typeform_id = @response_final["fields"][i]["id"]
      question.save
    end

    redirect_to user_path(current_user)
  end

  def destroy
    @survey = Survey.find(params[:id])
    @project_id = @survey.project_id
    if @survey.destroy
      redirect_to project_path(@project_id)
    end
  end

  def feature
    @projects = Project.where(user: current_user)
    @projects.each do |project|
      project.surveys.each do |survey|
        survey.featured = false
        survey.save
      end
    end

    @survey = Survey.find(params[:survey]["featured_survey"])
    @survey.featured = true
    @survey.save
    redirect_to user_path(current_user)
  end

  private

  def survey_params
    params.require(:survey).permit(:name, :project_id)
  end

  def set_survey
    # @survey = Survey.find(params[:id])
  end

    def add_to_typeform(survey)
    @all_questions = []

    survey.survey_questions.each do |question|
      question_hash = {
        "title": question.question,
        "type": question.q_type,
        "validations": {
          "required": true
        }
      }
      @all_questions << question_hash
    end
    begin
      RestClient.put(
          "https://api.typeform.com/forms/#{survey.typeform_id}", {
            title: survey.name,
            theme: {
                "href": "https://api.typeform.com/themes/#{@survey.project.theme}"
              },
            fields: @all_questions,
            welcome_screens: [
                {
                  "title": survey.name,
                  "properties": {
                    "description": @survey.welcome_messages[0].description,
                    "show_button": true,
                    "button_text": "start"
                  }
                }
            ]

          }.to_json, Authorization: "bearer #{@token}"
        )
    rescue Exception =>
        raise
    end
  end
end

app/views/surveys/_add_survey.html.erb
<%= link_to "#{survey.name}", survey_path(survey)  %>

app/views/surveys/_new_survey.html.erb
<div class="modal fade" id="create-new-survey" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create a New Survey</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for([project, Survey.new]) do |f| %>
          <%= f.input :name, label: false, placeholder: "this is what your survey recipients will see" %>
          <%= f.button :submit, class: "filled-button-survey" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/surveys/_questions-container.html.erb
<% @survey.survey_questions.each_with_index do |question, index| %>
  <div class=" question-card  " id="questions">
    <div class="card-body border-bottom ">
      <%= render 'survey_questions/add_question', survey: @survey, question: question, counter: index + 1 %>
    </div>
  </div>
<% end %>

app/views/surveys/index.html.erb
<% require "time"
%>

<% if current_user.projects.any? %>
<div class="container">
  <div class="row">
  	<h1 class="p-3 underline">My Surveys</h1>
  </div>

  <div class="row align-items-center border-bottom justify-content-center pt-4 pb-2 text-center">
  	<div class="col-md-1">
      	<span><strong>Bookmark</strong></span>
      </div>
      <div class="col-md-3">
      	<span><strong>Survey Name</strong></span>
      </div>
      <div class="col-md-2">
          <span><strong>Project</strong></span>
      </div>
      <div class="col-md-1">
      	<span><strong>Questions</strong></span>
      </div>
      <div class="col-md-1">
        <span><strong>Participants</strong></span>
      </div>
      <div class="col-md-2">
        <span><strong>Updated</strong></span>
      </div>
      <div class="col-md-1">
  	  <span><strong>Edit</strong></span>
  	</div>
      <div class="col-md-1">
      	<span><strong>Delete</strong></span>
      </div>
  </div>

  <% current_user.projects.reverse.each do |project| %>
  <% project.surveys.each do |survey| %>
  	<% time_diff = Time.now - survey.created_at %>
  	<% time_diff_days = (time_diff.fdiv(43200)).floor %>

  	<div class="row align-items-center border-bottom justify-content-center py-4 text-center hoverable">
  	<div class="col-md-1">
      	<a href="#" ><i class="far fas fa-star m-2 purple"></i></a>
      </div>
      <div class="col-md-3">
      	<%= link_to "#{survey.name}", survey_path(survey), style:"color:black"%>
      	<% if survey.completed %>
          	<i class="far fa-check-circle" style="color: purple"></i>
          <% end %>
      </div>
      <div class="col-md-2">
          <%= link_to "#{survey.project.name}", project_path(survey.project), style:"color:black" %>
      </div>
      <div class="col-md-1">
      	<a href="#"><i class="purple far fas fa-question-circle"></i></a>
  		<%= survey.survey_questions.count %>
      </div>
      <div class="col-md-1">
      	<a href="#"><i class="purple fas fa-users"></i></a>
       	<%= survey.participants.count %>
      </div>
      <div class="col-md-2">
        <%= time_diff_days.to_s + " Days Ago" if time_diff_days > 1  %>
        <%= "Yesterday" if time_diff_days == 1 %>
        <%= "Today" if time_diff_days == 0 %>
      </div>
      <div class="col-md-1">
  	  <a href="#"><i class="fan fas fa-edit"></i></a>
  	</div>
      <div class="col-md-1">
      	<%= link_to '<i class="fan fas fa-trash-alt"></i>'.html_safe, survey_path(survey), method: :delete, data: {confirm: "Are you sure?"} %>
      </div>
  </div>
  <% end %>
  <% end %>
  </div>

  <% else %>

  <div class="row">
    <h1 class="p-3 underline">My Surveys</h1>
  </div>

  <div class="row align-items-center justify-content-left pl-4 pt-4 pb-2 text-center">
    <p style="font-style: italic; opacity: 0.5">There are currently no surveys to be displayed</p>
  </div>



<% end %>

app/views/surveys/new.html.erb
<div class="c-survey-title">
  <h2>Title</h2>
<div class="survey-blanks">

<%= simple_form_for([@project, Survey.new]) do |f| %>
    <%= f.input :name, label: "What is the name of your survey?", placeholder: "grumpy cats" %>
  <div class="form-actions">
    <%= f.button :submit, class: "filled-button" %>
  </div>
  </div>
  <div class="back-button-div">
<%= link_to "Back", project_surveys_path, class: "button-back" %>
  <% end %>
</div>
</div>

app/views/surveys/show.html.erb
<div class="sweet-alert-username" data-username="<%= current_user.username %>" ></div>

<% if @survey.completed %>

  <%= link_to '<i class="fas purple fa-arrow-circle-left"></i>'.html_safe, project_path(@survey.project)%>

  <div class="row align-items-center justify-content-center p-2 text-center">
    <h1><%= @survey.name %></h1>
  </div>

      <div class="row align-items-center justify-content-center text-center">
        <!-- <div class="whole-form"> -->
          <%= link_to "Go To Answers", survey_question_answers_path(@survey), class: "button outline-button mx-2" %>
          <%= link_to "Go To Participants", participants_path(survey_id: @survey.id), class:  "button outline-button mx-2" %>
        <!-- </div> -->
      </div>

        <div class="row align-items-center justify-content-center p-2 text-center">
          <div class="col-12 col-lg-12 col-xl-12 mt-3">
              <div id="my-embedded-typeform" style="width: 100%; height: 400px;"></div>
          </div>
        </div>


        <div class="row align-items-center justify-content-center p-3 text-center">
          <div class="col-10 col-lg-10 col-xl-10">
          </div>
          <div class="col-2 col-lg-2 col-xl-2 text-right">
             <button id="share-survey" class="finish-editing p-2 share-survey" >Share Survey</button>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <!-- Embedded Form Script-->

  <script src="https://embed.typeform.com/embed.js" type="text/javascript"></script>
  <script type="text/javascript">
    window.addEventListener("DOMContentLoaded", function() {
      var el = document.getElementById("my-embedded-typeform");

      window.typeformEmbed.makeWidget(el, "https://admin.typeform.com/to/<%= @survey.typeform_id %>", {
        hideFooter: true,
        hideHeaders: true,
        opacity: 0
      });
    });
  </script>


<% else %>

  <div class="row">
    <div class="col-12 col-lg-12 col-xl-12">
      <div class="whole-form">
        <div class="row">
          <div class="col-12 col-lg-10 col-xl-12">
            <div class="form-intro" data-username="<%= current_user.username %>">
              <%= link_to '<i class="fas purple fa-arrow-circle-left"></i>'.html_safe, project_path(@survey.project)%>
              <h1><%= @survey.name %></h1>
              <div>
                <button id="edit-form-done" class="finish-editing m-2 p-2 share-survey">Publish</button>
                <%= link_to "", project_survey_path(@survey.project, @survey), id: "change-attribute", method: :put  %>
              </div>
            </div>
            <hr style="border-bottom: 2px solid #FCCD08">
          </div>
        </div>

        <div class="row">
          <div class="col-12 col-lg-10 col-xl-12">
            <div class="question-type">

              <div style="width: ">
              <% if @survey.welcome_messages.any? %>
                  <p style="font-size: 18px;"><strong>Description of the Survey:</strong></p>
                  <p><%=@survey.welcome_messages.last.description %></p>
              <% else %>
                <p style="font-size: 18px;"><strong>Please enter in a description of your survey! *</strong></p>
                  <button type="button" class=" outline-button mb-3" data-toggle="modal" data-target="#create-welcome-message">
                  Description of Survey
                  </button>
              <% end %>
              </div>
              <%# raise %>
              <%= render 'survey_questions/new_question', survey: @survey, question: @survey_question %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-12 col-lg-10 col-xl-12" id="questions-container">
            <%= render 'surveys/questions-container', survey: @survey %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="modal fade" id="create-welcome-message" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Description of Survey</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <%= simple_form_for([@survey, WelcomeMessage.new]) do |f| %>
          <%= f.input :description, label: false, placeholder: "This is what your respondents will see..." %>
          <%= f.button :submit, class: "button", value:"Add Description", class: "filled-button-survey" %>
        <% end %>
      </div>
    </div>
  </div>
</div>